name = "Cluster"
__version__ = "0.3"
__description__ = "Cluster - Unsupervised Icequake/Earthquake Clustering"
__license__ = "MIT"
__author__ = "William F. Jenkins II"
__email__ = "wjenkins [..at..] ucsd [..dot..] edu"
